# Generated by Django 4.1.5 on 2023-07-10 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slides', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slideelement',
            name='body',
            field=models.TextField(null=True),
        ),
    ]
