# Generated by Django 4.1.5 on 2023-07-11 00:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('slides', '0002_alter_slideelement_body'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transition',
            name='keyframes',
        ),
        migrations.AddField(
            model_name='transitionkeyframe',
            name='transition',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='keyframes', to='slides.transition'),
        ),
        migrations.AlterField(
            model_name='slideelement',
            name='body',
            field=models.TextField(blank=True, null=True),
        ),
    ]
