# Generated by Django 4.1.5 on 2023-07-11 00:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('slides', '0003_remove_transition_keyframes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='slide',
            name='transition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='slides', to='slides.transition'),
        ),
    ]
