# Generated by Django 4.1.5 on 2023-03-17 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('slides', '0005_remove_slide_deck_slide_segment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slideelement',
            name='slide',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='elements', to='slides.slide'),
            preserve_default=False,
        ),
    ]
