# Generated by Django 4.1.5 on 2023-08-14 18:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('slides', '0005_slideelement_video'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deck',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='segment',
            options={'ordering': ['order']},
        ),
        migrations.AlterModelOptions(
            name='show',
            options={'ordering': ('name',)},
        ),
        migrations.AddField(
            model_name='display',
            name='current_theme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='slides.theme'),
        ),
    ]
