# Generated by Django 4.1.5 on 2023-08-25 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slides', '0007_transitionkeyframe_out'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transitionkeyframe',
            options={'ordering': ('marker',)},
        ),
        migrations.AddField(
            model_name='slide',
            name='transition_duration',
            field=models.FloatField(default=1),
        ),
    ]
