# Generated by Django 4.1.5 on 2023-08-29 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slides', '0008_alter_transitionkeyframe_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='advance_between_decks',
            field=models.BooleanField(default=False),
        ),
    ]
