# Generated by Django 4.1.5 on 2023-09-08 19:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('slides', '0010_rename_advance_between_decks_show_advance_between_segments'),
    ]

    operations = [
        migrations.AddField(
            model_name='deck',
            name='default_transition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='slides.transition', unique='False'),
        ),
        migrations.AddField(
            model_name='deck',
            name='default_transition_duration',
            field=models.IntegerField(default=1),
        ),
    ]
