# Generated by Django 4.1.5 on 2023-09-08 21:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('slides', '0011_deck_default_transition_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deck',
            name='default_transition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='slides.transition'),
        ),
    ]
