# Generated by Django 4.1.5 on 2023-09-08 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slides', '0012_alter_deck_default_transition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deck',
            name='default_transition_duration',
            field=models.FloatField(default=1),
        ),
    ]
