# Generated by Django 4.1.5 on 2023-10-26 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slides', '0013_alter_deck_default_transition_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='advance_loop',
            field=models.BooleanField(default=False),
        ),
    ]
