# Generated by Django 4.1.5 on 2023-10-26 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('slides', '0014_show_advance_loop'),
    ]

    operations = [
        migrations.AddField(
            model_name='deck',
            name='default_auto_advance',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='deck',
            name='default_auto_advance_duration',
            field=models.FloatField(default=10),
        ),
        migrations.AddField(
            model_name='display',
            name='current_show',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='slides.show'),
        ),
        migrations.AddField(
            model_name='slide',
            name='auto_advance',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='slide',
            name='auto_advance_duration',
            field=models.FloatField(default=10),
        ),
    ]
