# Generated by Django 4.2.6 on 2023-10-31 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slides', '0015_deck_default_auto_advance_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='slide',
            options={'ordering': ['order', 'pk']},
        ),
        migrations.AddField(
            model_name='slide',
            name='order',
            field=models.FloatField(default=1),
        ),
    ]
