# Generated by Django 4.2.6 on 2023-12-10 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('slides', '0018_deck_slide_text_markup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='display',
            name='current_slide',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='slides.slide'),
        ),
    ]
