# Generated by Django 4.2.6 on 2024-04-17 09:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("slides", "0019_alter_display_current_slide"),
    ]

    operations = [
        migrations.AddField(
            model_name="display",
            name="previous_slide",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="slides.slide",
            ),
        ),
        migrations.AddField(
            model_name="display",
            name="slide_changed_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
