# Generated by Django 4.2.6 on 2024-07-09 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("slides", "0020_display_previous_slide_display_slide_changed_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="display",
            name="current_deck",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="current_displays",
                to="slides.deck",
            ),
        ),
    ]
