        # Generated by Django 5.1 on 2024-09-10 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("slides", "0024_mediaobject"),
    ]

    operations = [
        migrations.AddField(
            model_name="mediaobject",
            name="file_hash",
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
