# Generated by Django 5.1 on 2024-10-08 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("slides", "0025_mediaobject_file_hash"),
    ]

    operations = [
        migrations.AddField(
            model_name="mediaobject",
            name="title",
            field=models.CharField(default="", max_length=100),
            preserve_default=False,
        ),
    ]
