# Generated by Django 5.1 on 2024-10-08 23:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("slides", "0026_mediaobject_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="slideelement",
            name="media_object",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="elements",
                to="slides.mediaobject",
            ),
        ),
    ]
