# Generated by Django 5.1 on 2024-10-17 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("slides", "0027_slideelement_media_object"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mediaobject",
            name="media_type",
            field=models.CharField(
                choices=[
                    ("VIMEO_LIVE_EMBED", "Vimeo Live Embed"),
                    ("VIDEO", "Video"),
                    ("AUDIO", "Audio"),
                ],
                default="VIDEO",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="mediaobject",
            name="title",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
