# Generated by Django 5.1 on 2024-11-18 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("slides", "0029_deck_advance_in_loop"),
    ]

    operations = [
        migrations.AddField(
            model_name="display",
            name="default",
            field=models.BooleanField(
                default=False,
                help_text="Activate this display for any newly created shows",
            ),
        ),
    ]
