# Generated by Django 5.1 on 2024-11-20 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("slides", "0030_display_default"),
    ]

    operations = [
        migrations.CreateModel(
            name="Image",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.FileField(upload_to="image_intake/")),
                ("file_hash", models.CharField(blank=True, max_length=256, null=True)),
            ],
        ),
    ]
