# Generated by Django 5.1 on 2024-11-20 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("slides", "0031_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="image",
            name="file",
            field=models.ImageField(upload_to="images/"),
        ),
    ]
