# Generated by Django 5.1 on 2024-11-20 19:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("slides", "0032_alter_image_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="slideelement",
            name="image_object",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="elements",
                to="slides.image",
            ),
        ),
    ]
