# Generated by Django 5.1 on 2024-11-21 22:36
# Custom migration

from django.db import migrations
import hashlib

def get_file_hash(file):
    hash_func = hashlib.new('sha256')
    with open(file, 'rb') as file:
        while chunk := file.read(65536):
            hash_func.update(chunk)
    return hash_func.hexdigest()

def forward_func(apps, schema_editor):
    media_object_model = apps.get_model('slides', 'MediaObject')
    for media_object in media_object_model.objects.all():
        if media_object.final_file and not media_object.file_hash:
            media_object.file_hash = get_file_hash(media_object.final_file.path)
            media_object.save()

def reverse_func(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("slides", "0035_remove_slideelement_image"),
    ]

    operations = [
        migrations.RunPython(forward_func, reverse_func),
    ]
