# Generated by Django 5.1 on 2024-11-22 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("slides", "0036_hash_media_objects"),
    ]

    operations = [
        migrations.AddField(
            model_name="slideelement",
            name="missing_image_object",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="slideelement",
            name="missing_media_object",
            field=models.BooleanField(default=False),
        ),
    ]
