# Generated by Django 5.1 on 2024-11-22 04:07
import hashlib

from django.db import migrations

def forward_func(apps, schema_editor):
    media_object_model = apps.get_model('slides', 'MediaObject')
    for media_object in media_object_model.objects.all():
        if media_object.embed_url and not media_object.file_hash:
            media_object.file_hash = hashlib.sha256(media_object.embed_url.encode("utf-8")).hexdigest()
            media_object.save()

def backward_func(apps, schema_editor):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ("slides", "0037_slideelement_missing_image_object_and_more"),
    ]

    operations = [
        migrations.RunPython(forward_func, backward_func),
    ]
