# Generated by Django 5.1 on 2024-11-24 23:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("slides", "0038_hash_media_embeds"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="deck",
            name="script",
        ),
    ]
