# Generated by Django 5.1 on 2025-02-07 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("slides", "0039_remove_deck_script"),
    ]

    operations = [
        migrations.AlterField(
            model_name="slide",
            name="order",
            field=models.FloatField(null=True),
        ),
    ]
