# Generated by Django 5.1 on 2025-03-17 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("slides", "0041_alter_image_options_alter_mediaobject_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="transition",
            name="default",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="slideelement",
            name="css_class",
            field=models.CharField(max_length=100, verbose_name="CSS Class"),
        ),
    ]
