# Generated by Django 5.1 on 2025-03-17 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("slides", "0042_transition_default_alter_slideelement_css_class"),
    ]

    operations = [
        migrations.AddField(
            model_name="theme",
            name="default",
            field=models.BooleanField(default=False),
        ),
    ]
