# Generated by Django 5.1 on 2025-04-16 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("slides", "0044_mediaobject_thumbnail"),
    ]

    operations = [
        migrations.AddField(
            model_name="mediaobject",
            name="needs_transcode",
            field=models.BooleanField(default=True),
        ),
    ]
