# Generated by Django 5.1 on 2025-04-16 20:15

from django.db import migrations

def forward_func(apps, schema_editor):
    media_object_model = apps.get_model('slides', 'MediaObject')
    for media_object in media_object_model.objects.all():
        if media_object.type == 'VIDEO' and media_object.final_file:
            media_object.needs_transcode = False

class Migration(migrations.Migration):

    dependencies = [
        ("slides", "0045_mediaobject_needs_transcode"),
    ]

    operations = []
