# Generated by Django 5.1 on 2025-04-22 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("slides", "0046_existing_mediaobject_needs_transcode_false"),
    ]

    operations = [
        migrations.RenameField(
            model_name="mediaobject",
            old_name="thumbnail",
            new_name="thumbnail_image",
        ),
    ]
