# Generated by Django 5.1 on 2025-07-30 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("slides", "0047_rename_thumbnail_mediaobject_thumbnail_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mediaobject",
            name="needs_transcode",
            field=models.BooleanField(
                blank=True, default=True, verbose_name="Transcode this Media Object"
            ),
        ),
    ]
