# Generated by Django 5.1 on 2025-07-30 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("slides", "0048_alter_mediaobject_needs_transcode"),
    ]

    operations = [
        migrations.AlterField(
            model_name="slideelement",
            name="body",
            field=models.TextField(blank=True, default="", null=True),
        ),
    ]
