# Generated by Django 5.1 on 2025-08-02 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("slides", "0049_alter_slideelement_body"),
    ]

    operations = [
        migrations.AddField(
            model_name="show",
            name="import_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
