# Generated by Django 5.1 on 2025-08-28 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('slides', '0050_show_import_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='segment',
            name='local_slides_post',
        ),
        migrations.RemoveField(
            model_name='segment',
            name='local_slides_pre',
        ),
    ]
