# Generated by Django 5.1 on 2025-08-28 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slides', '0051_remove_segment_local_slides_post_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='segment',
            name='details',
            field=models.TextField(blank=True, null=True),
        ),
    ]
