# Generated by Django 5.1 on 2025-09-30 15:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slides', '0052_segment_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='RemoteSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_url', models.URLField(help_text='URL of the remote source. This should be a JSON endpoint which returns an index of available content.')),
                ('name', models.CharField(help_text='Local name of the remote source.', max_length=200)),
                ('refresh_every', models.IntegerField(help_text='How often to refresh this remote source, in minutes')),
                ('metadata_last_fetched', models.DateTimeField(default=datetime.datetime.now)),
                ('shows_url', models.URLField(blank=True, null=True)),
                ('themes_url', models.URLField(blank=True, null=True)),
                ('decks_url', models.URLField(blank=True, null=True)),
                ('images_url', models.URLField(blank=True, null=True)),
                ('media_url', models.URLField(blank=True, null=True)),
                ('transitions_url', models.URLField(blank=True, null=True)),
                ('displays_url', models.URLField(blank=True, null=True)),
                ('index_data', models.JSONField(blank=True, null=True)),
            ],
        ),
    ]
