# Generated by Django 5.1 on 2025-11-27 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slides', '0053_remotesource'),
    ]

    operations = [
        migrations.AlterField(
            model_name='segment',
            name='order',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='transitionkeyframe',
            name='marker',
            field=models.CharField(help_text='from, 2%, 50%, to, etc.', max_length=30),
        ),
    ]
