# Generated by Django 6.1.1 on 2026-10-06 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('slides', '0054_alter_segment_order_alter_transitionkeyframe_marker'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slideelement',
            name='video',
        ),
    ]
