# Generated by Django 6.1.1 on 2026-10-06 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slides', '0055_remove_slideelement_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='themerule',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='themevariant',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='themevariantrule',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
