# Generated by Django 6.1.1 on 2026-10-06 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slides', '0056_themerule_description_themevariant_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='themerule',
            name='base_rule',
            field=models.BooleanField(default=False, help_text='If true, this rule will be selectable as a type when creating slide elements.'),
        ),
    ]
