# Generated by Django 6.1.1 on 2026-10-07 15:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slides', '0057_alter_themerule_base_rule'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThemeFont',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('font_file', models.FileField(upload_to='fonts/')),
                ('font_face_name', models.CharField(help_text='The font face name by which to access this font in rule properties', max_length=100)),
                ('theme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fonts', to='slides.theme')),
            ],
        ),
    ]
