# Generated by Django 6.1.1 on 2026-10-07 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slides', '0058_themefont'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='themerule',
            options={'ordering': ['base_rule', '-css_selector']},
        ),
        migrations.RemoveField(
            model_name='themefont',
            name='font_face_name',
        ),
        migrations.AddField(
            model_name='themefont',
            name='properties',
            field=models.TextField(help_text='CSS @font-face properties for this font family.', null=True),
        ),
        migrations.AlterField(
            model_name='theme',
            name='css',
            field=models.TextField(help_text='CSS Entries here cannot be selected as element types or modifiers.'),
        ),
    ]
