# Generated by Django 4.1.5 on 2023-02-06 17:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Deck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('custom_css', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Display',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('pixel_width', models.IntegerField(default=1920)),
                ('pixel_height', models.IntegerField(default=1080)),
                ('custom_css', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SlideElement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('css_class', models.CharField(max_length=100)),
                ('body', models.TextField()),
                ('order', models.IntegerField()),
            ],
            options={
                'ordering': ['-order'],
            },
        ),
        migrations.CreateModel(
            name='Slide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('deck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slides', to='slides.deck')),
                ('elements', models.ManyToManyField(related_name='slide', to='slides.slideelement')),
            ],
        ),
        migrations.CreateModel(
            name='Show',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('displays', models.ManyToManyField(blank=True, to='slides.display')),
            ],
        ),
        migrations.CreateModel(
            name='Segment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('order', models.IntegerField()),
                ('included_deck', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='slides.deck')),
                ('local_slides_post', models.ManyToManyField(blank=True, related_name='post_slides', to='slides.slide')),
                ('local_slides_pre', models.ManyToManyField(blank=True, related_name='pre_slides', to='slides.slide')),
            ],
            options={
                'ordering': ['-order'],
            },
        ),
        migrations.AddField(
            model_name='display',
            name='current_slide',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='slides.slide'),
        ),
        migrations.AddField(
            model_name='display',
            name='segments',
            field=models.ManyToManyField(blank=True, to='slides.segment'),
        ),
    ]
