# Generated by Django 4.1.5 on 2023-02-06 21:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('slides', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='segment',
            name='show',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='segments', to='slides.show'),
            preserve_default=False,
        ),
    ]
