# Generated by Django 4.1.5 on 2023-02-06 22:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('slides', '0002_segment_show'),
    ]

    operations = [
        migrations.AlterField(
            model_name='segment',
            name='included_deck',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='slides.deck'),
        ),
    ]
